nama            = input('Masukkan nama anda: ')
ttl             = input('Masukkan tempat tanggal lahir anda: ')
alamat          = input('Masukkan alamat anda: ')
No              = input('Masukkan nomor telepon anda: ')
programStudi    = input('Masukkan program studi anda: ')
hobi            = input('Masukkan hobi anda: ')

print()

print('==========================')
print('=====  BIODATA DIRI  =====')
print('==========================')
print('Nama Lengkap  : ', nama)
print('TTL           : ', ttl)
print('Alamat        : ', alamat)
print('Nomor Telepon : ', No)
print('Program Studi : ', programStudi)
print('Hobi          : ', hobi)